version: "3.3"

services:
  uptime-kuma:
    image: elestio/uptime-kuma:${SOFTWARE_VERSION_TAG}
    container_name: uptime-kuma
    restart: always
    healthcheck:
      disable: true
    volumes:
      - ./data:/app/data
    ports:
      - "172.17.0.1:3001:3001"
